server:
  port: 8082
spring:
  application:
    name: ShopBackend
  servlet:
    context-path: /ShopmeAdmin
  datasource:
    url: jdbc:mysql://localhost:3306/shopping?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: ameda
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect